select * from customers limit 10


--Q1. What is the total revenue generated by male vs. female?
select gender, Sum(purchase_amount) as Total_Sales
from customers
group by gender

--Q2. Find customers who used a discount but still spent more than average purchase amount

select customer_id, purchase_amount
from customers 
where discount_applied='Yes' and purchase_amount> (select avg(purchase_amount) from customers)


--Q3. Whch are the top 5 products with highest average review ratings/
select item_purchased, round(avg(review_rating::numeric),2) as "Average review ratings"
from customers
group by item_purchased
order by avg(review_rating)
limit 5;


--Q4. Copmpare the average shipping charges for standard and express delivery

select shipping_type, round(avg(purchase_amount),2)
from customers
where shipping_type in ('Standard','Express')
group by shipping_type


--Q5. Do subscribed customers pay more? Compare the average spend and total revenue between subscribed and non-subscribed customers

select subscription_status, count(customer_id), round(avg(purchase_amount),2) as average_spend, Sum(purchase_amount) as total_revenue
from customers
group by subscription_status
order by total_revenue, average_spend desc


--Q6. Which 5 products have highest purchase percentage with discounts applied?

select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customers
group by item_purchased
order by discount_rate desc
limit 5;


--Q7. Segment customers into 'New','Returning','Loyal' based on their total number of purchases and show the total number

With customer_type AS ( 
select customer_id,previous_purchases,
case
 	when previous_purchases=1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	End as customer_segment
from customers
)
select customer_segment, count(*) as "total_customers"
from customer_type
group by customer_segment;


--Q8. What are the 3 most purchased products within each category?

With items_count As(
select category,item_purchased,
count(customer_id) as total_orders,
Row_number() over (partition by category order by count(customer_id)desc) as item_rank
from customers
group by category, item_purchased
) 
select item_rank, category, item_purchased, total_orders
from items_count
where item_rank<=3;


--Q9. Are customers who are repeat buyers(more than 5 previous purchases) likely to subscribe?

select subscription_status, count(customer_id)as repeat_buyers
from customers
where previous_purchases>5
group by subscription_status


--Q10. Find the revenue contribution of each age group?

select age_group, sum(purchase_amount) as total_revenue
from customers
group by age_group
order by total_revenue desc;
